# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:boqii.123@tcp(172.16.76.194:13396)/go_gateway_demo?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100